---

  - name: install zsh
    apt:
      name=zsh
      state=present

  - name: clone oh-my-zsh
    git:
      repo={{ git_repo }}
      dest={{ path }}

  - name: copy basic zsh config
    command: cp {{ default_template }} /root/.zshrc  

  - name: set zsh as default shell
    lineinfile:
      line="exec zsh"
      dest="{{ bashrc_path }}"

  - name: copy zsh configuration
    copy:
      src="{{ zshrc_source }}"
      dest="{{ zshrc_destination }}"
