---

  - name: download rustup
    get_url:
      url: "{{ rustup_url }}"
      dest: "{{ temp_directory_path }}/{{ rustup_archive_name }}"
    become: yes
    become_user: vagrant

  - name: install rustup and rust nightly
    shell: "sh {{ rustup_archive_name }} --default-toolchain nightly -y"
    args:
      chdir: "{{ temp_directory_path }}"
    become: yes
    become_user: vagrant
