---

  - name: add neovim repository
    apt_repository:
      repo: ppa:neovim-ppa/stable

  - name: install neovim
    apt:
      name=neovim
      state=present
      update_cache=yes

  - name: ensure neovim configuration directory exists
    file:
      path=/home/vagrant/.config/nvim
      state=directory

  - name: copy neovim configuration
    copy:
      src=roles/neovim/files/init.vim
      dest=/home/vagrant/.config/nvim/init.vim
