---

  - name: add neovim repository
    apt_repository:
      repo: ppa:neovim-ppa/stable

  - name: install neovim
    apt:
      name=neovim
      state=present
      update_cache=yes

  - name: ensure neovim configuration directory exists
    file:
      path=/home/vagrant/.config/nvim
      state=directory
    become: yes
    become_user: vagrant

  - name: copy neovim configuration
    copy:
      src=roles/neovim/files/init.vim
      dest=/home/vagrant/.config/nvim/init.vim
    become: yes
    become_user: vagrant

  - name: ensure neovim pluggin directory exists
    file:
      path=/home/vagrant/.local/share/nvim/site/autoload
      state=directory
    become: yes
    become_user: vagrant

  - name: install vim-plug for pluggins management
    get_url:
      url=https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
      dest=/home/vagrant/.local/share/nvim/site/autoload/plug.vim
    become: yes
    become_user: vagrant

  - name: install python3 support for neovim
    pip:
      name=neovim
      executable=pip3
    become: yes

  - name: install language server client plugin into neovim
    shell: nvim +PlugInstall +UpdateRemotePlugins +qa
    become: yes
    become_user: vagrant
