filetype plugin indent on
set tabstop=4
set shiftwidth=4
set expandtab
syntax on

set colorcolumn=80
set nu

set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 0
let g:syntastic_auto_loc_list = 0
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 1
let g:syntastic_enable_highlighting = 0
let g:syntastic_rust_checkers = ['cargo']

execute pathogen#infect()

highlight link SyntasticErrorLine error
